site_name: electronics notes
markdown_extensions: 
 - mdx_math
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']
pages:
- Home: index.md
- Atmel: atmel.md
- Bus Pirate: buspirate.md
- Cookbook: cookbook.md
- Diodes: diode.md
- Filters: filters.md
- The 555 chip: fivefivefive.md
- Integrated circuit: ic.md
- Logic circuits: logic.md
- Impedance: impedance.md
- Laws: laws.md
- Leds: led.md
- Motors: motors.md
- OpAmp: opamp.md
- Oscillators: oscillator.md
- Protocols: protocols.md
- Prototyping: Prototyping.md
- Eagle: eagle.md
- KiCad: kicad.md
- Sampling: sampling.md
- Sensors: Sensors.md
- Signal: signal.md
- Soldering: soldering.md
- Simulation: simulation.md
- Tools: tools.md
- Transistors: transistor.md
- Power management: voltagereg.md
- FPGA: fpga.md
theme: readthedocs
